pipeline:
  name: Tom Testing
  identifier: Tom_Testing
  projectIdentifier: Andy_and_Tom_Testing
  orgIdentifier: Deployment_Services
  tags: {}
  stages:
    - stage:
        name: deployk8s
        identifier: deployk8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginx
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: pdevpre
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pre
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: K8sDryRun_1
                  identifier: K8sDryRun_1
                  spec: {}
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
